### PR TITLE
Fetch all files from a package

### PR DESCRIPTION
**Pull request by maxbth**
I added the ability to fetch all files from a package, tell me what you think about it :)

### CODE REVIEW

**Comment by Shosta** [comment]
That would be indeed a very nice addition. 
I miss that option as well.
@pflammertsma , would you consider to merge it to the main branch?

**Comment by pflammertsma** [comment]
@Shosta I've reviewed it, made some fixes and merged it into master.

**Comment by pflammertsma** [comment]
@maxoumime Thanks for your contribution!

**Comment by maxoumime** [comment]
Happy to help!

**Comment by Shosta** [comment]
That is awesome. Thanks a lot.

**Pull request merged**
